name: BULPearl
version: ${project.version}
description: ${project.description}
author: AliHaine
main: com.alihaine.bulpearl.BULpearl
api-version: 1.13
commands:
  bulpearl:
    description: Reload config